workspace '../XNGMarkdownParser'
xcodeproj 'Example.xcodeproj'

target "Example" do
  pod "XNGMarkdownParser", :path => "../XNGMarkdownParser.podspec"
end

target "ExampleTests" do
  pod 'Expecta', '~> 0.3.1'
  pod 'FBSnapshotTestCase'
end

post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MOMC_NO_INVERSE_RELATIONSHIP_WARNINGS'] = 'YES'
    end
  end
end
