#!/bin/bash
#
# Copyright 2011-2014 NimbusKit
#
# Builds a Markdown tokenizer using flex - http://flex.sourceforge.net/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

flex --prefix=markdown --nounput markdown.grammar

cat MarkdownTokenizerPrefix > MarkdownTokenizer.cpp
cat lex.markdown.c >> MarkdownTokenizer.cpp

rm lex.markdown.c

mv MarkdownTokenizer.cpp ../src/MarkdownTokenizer.m
cp MarkdownTokens.cpp ../src/MarkdownTokens.m
cp MarkdownTokens.h ../src/MarkdownTokens.h
