//
// Copyright 2012 Jeff Verkoeyen
//
// Autogenerated by flex using Jeff Verkoeyen's Markdown grammar
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#include "MarkdownTokens.h"

#line 3 "lex.markdown.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE markdownrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via markdownrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void markdownrestart (FILE *input_file ,yyscan_t yyscanner );
void markdown_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE markdown_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void markdown_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void markdown_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void markdownpush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void markdownpop_buffer_state (yyscan_t yyscanner );

static void markdownensure_buffer_stack (yyscan_t yyscanner );
static void markdown_load_buffer_state (yyscan_t yyscanner );
static void markdown_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER markdown_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE markdown_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE markdown_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE markdown_scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *markdownalloc (yy_size_t ,yyscan_t yyscanner );
void *markdownrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void markdownfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer markdown_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        markdownensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            markdown_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        markdownensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            markdown_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 14
#define YY_END_OF_BUFFER 15
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[308] =
    {   0,
        0,    0,   15,   13,   12,   12,   12,   13,   13,   13,
       13,   13,   13,   13,   13,    5,   13,    0,    0,   11,
        0,    0,    0,    1,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    1,    0,    5,    5,    9,    0,
        0,   11,   10,    0,    1,    0,    1,    0,    0,    0,
        0,    0,    7,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    5,    6,
        6,    0,    0,    0,    0,    0,    0,    2,    7,    0,
        7,    7,    0,    7,    7,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    6,    0,    0,    0,

        0,    0,    0,    2,    4,    5,    2,    2,    6,    0,
        0,    0,    0,    0,    7,    0,    7,    7,    7,    0,
        7,    7,    7,    7,    0,    0,    0,    0,    0,    7,
        0,    0,    0,    0,    6,    0,    0,    0,    0,    0,
        5,    0,    6,    3,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    0,    7,    7,    0,    0,
        0,    8,    7,    7,    0,    0,    6,    0,    5,    3,
        7,    7,    7,    7,    0,    7,    7,    7,    7,    7,
        0,    7,    7,    7,    7,    7,    0,    7,    7,    7,
        7,    0,    0,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    0,    7,    7,    7,    7,
        7,    7,    0,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    0,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    0,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    6,    7,    6,    6,    6,    6,    8,
        9,   10,    6,    6,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    6,    6,
       16,    6,    6,    6,   14,   14,   14,   14,   14,   17,
       18,   19,   18,   18,   18,   18,   18,   18,   18,   20,
       18,   18,   21,   22,   18,   18,   18,   18,   18,   18,
       23,   24,   25,    6,   26,    6,   14,   14,   14,   14,

       14,   27,   18,   28,   18,   18,   18,   18,   18,   18,
       18,   29,   18,   18,   30,   31,   18,   18,   18,   18,
       18,   18,    6,    6,    6,   32,    1,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,

       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33
    } ;

static yyconst flex_int32_t yy_meta[34] =
    {   0,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        3,    4,    5,    3,    2,    6,    3,    3,    3,    3,
        3,    3,    2,    3,    2,    2,    3,    3,    3,    3,
        3,    2,    3
    } ;

static yyconst flex_int16_t yy_base[351] =
    {   0,
        0,   27,  607,  591,  587,  585,   32,   33,   43,   55,
       56,  583,   87,   76,   77,   78,   87,  565,   83,  561,
       36,   90,   95,   93,  548,  112,  145,   96,  106,   92,
        0,  171,   81,  139,   94,   80,  537,  149,  531,  146,
      150,  525,  108,   37,  522,  512, 1593,  167,  157,  111,
      161,  188,  211,  244,  497,  270,  174,  167,  189,  238,
      167,  476,  240,  165,  241,  177,  179,  223,  220, 1593,
      488,  190,  486,  482,  267,  210,  249,  266,  287,  320,
      463,  337,  370,    0,  396,  269,  275,  141,   98,  298,
      261,  466,  436,  252,  312,  313,  422,  309,  416,  366,

      403,  349,  320,  350,  293,  287,  411, 1593,  398,  285,
      384,  378,  375,  335,    0,  423,    0,  449,    0,  476,
      367,  502,  519,  366,  339,  388,  329,  386,  387,  404,
      392,  333,  542,  404,  336,  378,  334,  419,  324,  429,
      400,  333,  331,  330,    0,  568,  423,  429,    0,  594,
      446,  447,  456,  177,  291,  456,  467,  425,  468,  472,
      621,  462,    0,  653,  474,  483,  274,  265,  276, 1593,
      502,  494,  250,  501,  506,  510,  525,  525,  534,  420,
      540,  225,  679,  548,  539,  705,  549,  722,  745,  778,
      560,  564,  566,  575,  568,  804,  586,  233,  587,  592,

      594,  830,  645,  646,  647,  651,  222,  847,  880,    0,
      906,  652,  671,  672,  673,  678,  687,  698,  703,  710,
      721,  744,  923,  946,  979,  157, 1005,  770,  771,  772,
      776,  777,  796,  797,  798,  802,  803,  822, 1022, 1055,
      151, 1072, 1105,    0, 1131,  823,  828,  845, 1157,  846,
      872,  873,  874,  878,  879,    0, 1173,    0, 1199,    0,
     1226,  126, 1252,  898,  899,  900,  613,  904,  905,  921,
     1278,    0, 1293,  922,    0, 1319,  944,  971,  972,  973,
      977, 1345,  978,  997,  998,  999, 1004, 1021, 1047, 1048,
     1049, 1053, 1054, 1070, 1071, 1097, 1098, 1099, 1103, 1104,

     1123, 1124, 1125, 1129, 1130, 1152, 1593, 1361, 1367, 1373,
     1379, 1385, 1391, 1397, 1403, 1409, 1415, 1421, 1427, 1433,
     1439, 1445, 1449, 1455, 1461, 1467, 1473, 1479, 1485,  132,
     1490, 1496, 1502, 1508, 1512,   79, 1517, 1521, 1525, 1529,
     1534, 1539, 1544, 1550, 1556, 1562, 1568, 1574, 1580, 1586
    } ;

static yyconst flex_int16_t yy_def[351] =
    {   0,
      307,    1,  307,  308,  308,  307,  308,  309,  307,    9,
        9,  310,  311,  312,  308,  313,    9,  308,  307,  307,
      308,  309,  314,  315,    9,  308,  316,    9,    9,  310,
        9,    9,  312,  317,  318,  319,  313,  313,  308,    9,
      307,  307,  307,  308,  308,  314,  307,  314,  315,  320,
      321,   26,    9,  322,    9,    9,    9,    9,  310,  323,
       32,  317,  317,  318,  324,  325,  319,  319,  313,  307,
      314,  308,  320,  307,  320,  321,  326,  308,   53,  327,
       53,   79,  328,   53,   53,  323,   56,  308,    9,    9,
      329,   86,  330,   86,  331,   32,  317,  308,  324,  324,

      307,  325,  332,  308,  319,  313,  308,  307,  320,  308,
      326,  307,  326,  308,   79,  333,   79,   79,   82,  334,
       53,   53,  335,   85,  336,   56,  308,  329,  329,  335,
      337,   86,   86,   32,  324,  308,  332,  332,  307,  308,
      313,  307,  326,  308,   79,   79,  338,  118,   82,   82,
      130,  122,  130,  339,  130,  340,   85,  338,  341,   56,
      307,  329,  130,  130,  133,   32,  332,  307,  313,  307,
      338,  146,  171,  171,  342,  118,  339,  150,  122,  339,
      343,  130,  130,   85,  171,  171,   56,  161,  161,  344,
      164,  133,   32,  146,  171,  186,  118,  177,  150,  122,

      177,  177,  183,   85,  186,   56,  189,  161,  345,  189,
      189,  164,  133,  146,  196,  118,  150,  122,  202,  183,
       85,  186,  161,  189,  346,  189,  189,  211,  164,  133,
      146,  196,  118,  150,  122,  202,  183,  186,  224,  347,
      224,  239,  348,  224,  224,  227,  211,  164,   86,  146,
      196,  150,  202,  183,  186,  239,  349,  239,  239,  242,
      350,  224,  224,  245,  227,  211,  130,  196,  202,  183,
      171,  239,  239,  259,  242,  242,  263,  245,  227,  211,
      196,  177,  273,  259,  276,  263,  245,  227,  211,  273,
      259,  276,  263,  245,  227,  273,  259,  276,  263,  245,

      273,  259,  276,  263,  273,  276,    0,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307
    } ;

static yyconst flex_int16_t yy_nxt[1627] =
    {   0,
        4,    5,    6,    4,    7,    4,    4,    4,    4,    8,
        9,    4,    4,    9,    4,    4,   10,    9,   11,    9,
        9,    9,   12,   13,    4,   14,   10,   11,    9,    9,
        9,   15,    9,   16,   19,   23,   21,   17,   43,   43,
       44,   44,   24,   18,   18,   19,   18,   18,   18,   18,
       18,   18,   18,   25,   26,   18,   25,   18,   18,   25,
       25,   25,   25,   25,   25,   18,   27,   18,   18,   25,
       25,   25,   25,   25,   18,   25,   28,   29,   34,   19,
       19,  158,   19,   34,   38,   28,   29,   18,   18,   19,
       18,   39,   23,   41,   19,   50,   65,   40,   41,   45,

       32,   35,   51,   32,   47,   48,   45,   52,   36,   52,
       48,   68,   88,   32,   19,   57,   59,   52,   41,   66,
       74,   75,   53,   41,   57,   53,   75,   58,   53,   53,
       53,   53,   53,   53,  130,   54,   58,  223,   53,   53,
       53,   53,   53,   19,   53,   18,   18,   19,   18,   63,
       39,   19,   70,  127,   63,   69,   40,   52,   56,   50,
       41,   56,  223,   77,   47,   41,   72,   65,  223,   71,
       78,   56,   31,   60,   31,   31,   47,   48,   52,  103,
       96,   19,   48,   96,   61,   52,   90,   61,   88,  154,
       98,   19,   19,   96,   89,   90,   91,   61,   79,  107,

      181,   79,  104,   89,   79,   79,   79,   79,   79,   79,
       68,   80,   77,   59,   79,   79,   79,   79,   79,  110,
       79,   81,   19,   82,   81,   19,  106,   81,   81,   81,
       81,   81,   81,  223,   83,   70,  125,   81,   81,   81,
       81,   81,   97,   81,   18,   18,   19,   18,   92,   93,
       63,  100,   70,   41,  105,   63,  100,   85,  112,  113,
       85,   95,   94,   19,  113,   47,  101,  307,   19,  109,
       85,   55,   86,   55,   55,  114,   74,   75,   19,   92,
      125,   52,   75,   87,   41,  129,   87,   19,  126,   19,
      170,  126,   95,  141,  114,   19,   87,  115,   18,  139,

      115,  126,  125,  115,  115,  115,  115,  115,  115,   52,
      116,   19,   88,  115,  115,  115,  115,  115,   89,  115,
       18,   18,   19,   18,  105,  133,  134,   89,  133,  134,
      138,   19,   19,  118,  107,  138,  118,   19,  133,  134,
      112,  161,  170,   94,  144,  139,  118,  119,  307,  168,
      119,  103,   19,  119,  119,  119,  119,  119,  119,  139,
      120,  101,  159,  119,  119,  119,  119,  119,  135,  119,
       18,   18,   19,   18,  136,  140,  100,  143,   52,  157,
       19,  100,  157,  122,  112,  113,  122,  142,   19,   19,
      113,  101,  157,  112,  162,  162,  122,   84,  123,   84,

       84,  160,   19,  140,  160,  164,  169,   74,  164,  124,
      129,  129,  124,   19,  160,   93,  154,  166,  164,  307,
      166,  167,  124,   18,   18,   19,   18,  156,  108,  138,
      166,   19,  154,  173,  138,  154,  146,  154,   41,  146,
      307,  101,  176,  181,  139,  176,  175,   47,  175,  146,
      117,  147,  117,  117,  144,  176,  153,  125,   70,  131,
      179,   41,  148,  179,   19,  148,  153,  125,   70,  183,
      162,   41,  183,  179,   52,  148,   18,   18,   19,   18,
      184,  186,  183,  184,  186,  187,  129,  192,  187,  150,
      192,  108,  150,  184,  186,   74,  193,   47,  187,  193,

      192,   47,  150,  121,  151,  121,  121,  194,   52,  193,
      194,  174,  173,   52,  154,  152,  307,   41,  152,  196,
      194,   47,  196,  197,   19,  175,  197,   42,  152,  153,
       93,  154,  196,   19,   41,  198,  197,  154,  199,   19,
       41,  199,  156,  132,  132,  132,  132,  200,  181,  174,
      200,  199,   94,  202,  307,  165,  202,  307,  165,   52,
      200,  204,  206,   42,  204,  206,  202,   19,  165,  145,
      171,  145,  145,  212,  204,  206,  212,  213,  174,   25,
      213,  172,   25,  307,  172,   19,  212,   20,  214,   19,
      213,  214,   25,   19,  172,  149,  177,  149,  149,  216,

      217,  214,  216,  217,  180,  218,  307,  178,  218,  307,
      178,  307,  216,  217,  163,  163,  163,  163,  218,  307,
      178,  188,  188,   19,  188,   18,  188,  188,  188,  188,
      188,  189,  188,  188,  189,  188,  188,  189,  189,  189,
      189,  189,  189,  188,  190,  188,  188,  189,  189,  189,
      189,  189,  188,  189,  163,  163,  163,  163,  220,  221,
      222,  220,  221,  222,   25,  229,  191,   25,  229,  191,
      307,  220,  221,  222,  307,  307,  307,   25,  229,  191,
      182,  182,  182,  182,  230,  231,  232,  230,  231,  232,
      125,  233,  203,  307,  233,  203,  307,  230,  231,  232,

      234,  307,  307,  234,  233,  203,  185,  185,  185,  185,
      307,  235,  307,  234,  235,  174,  236,  307,  205,  236,
      307,  205,  307,  237,  235,  307,  237,  307,  307,  236,
      307,  205,  188,  307,   81,  188,  237,   81,  188,  188,
      188,  188,  188,  188,  307,  188,  307,   81,  188,  188,
      188,  188,  188,  307,  188,  207,  208,  238,  207,  307,
      238,  207,  207,  207,  207,  207,  207,  307,  209,  307,
      238,  207,  207,  207,  207,  207,  307,  207,  188,  188,
       19,  188,   31,  247,  248,  249,  247,  248,  249,  250,
      251,  211,  250,  251,  211,  307,  247,  248,  249,  307,

      307,  307,  250,  251,  211,  195,  195,  195,  195,  115,
      252,   81,  115,  252,   81,  253,  254,  215,  253,  254,
      215,  307,  115,  252,   81,  307,  307,  307,  253,  254,
      215,  201,  201,  201,  201,  255,  265,  307,  255,  265,
      180,  266,  307,  219,  266,  307,  219,  307,  255,  265,
      307,  307,  307,  307,  266,  307,  219,  224,  267,  115,
      224,  267,  115,  224,  224,  224,  224,  224,  224,  307,
      225,  267,  115,  224,  224,  224,  224,  224,  307,  224,
      188,  188,   19,  188,   55,  268,  119,  269,  268,  119,
      269,  270,  271,  227,  270,  271,  227,  307,  268,  119,

      269,  307,  307,  307,  270,  271,  227,  210,   60,  210,
       31,  278,  279,  280,  278,  279,  280,  281,  282,  228,
      281,  282,  228,  307,  278,  279,  280,  307,  307,  307,
      281,  282,  228,  239,  155,  284,  239,  155,  284,  239,
      239,  239,  239,  239,  239,  307,  240,  155,  284,  239,
      239,  239,  239,  239,  307,  239,  241,  286,  242,  241,
      286,  307,  241,  241,  241,  241,  241,  241,  307,  243,
      286,  307,  241,  241,  241,  241,  241,  307,  241,  188,
      188,   19,  188,   84,  287,  288,  289,  287,  288,  289,
      174,  290,  245,  174,  290,  245,  307,  287,  288,  289,

      307,  307,  307,  174,  290,  245,  226,   86,  226,   55,
      291,  292,  293,  291,  292,  293,  223,  294,  246,  307,
      294,  246,  307,  291,  292,  293,  307,  307,  307,  307,
      294,  246,  256,  188,  295,  256,  307,  295,  256,  256,
      256,  256,  256,  256,  307,  257,  307,  295,  256,  256,
      256,  256,  256,  307,  256,  188,  188,   19,  188,  117,
      207,  296,  297,  207,  296,  297,  298,  299,  259,  298,
      299,  259,  307,  207,  296,  297,  307,  307,  307,  298,
      299,  259,  260,  300,  207,  260,  300,  207,  260,  260,
      260,  260,  260,  260,  307,  261,  300,  207,  260,  260,

      260,  260,  260,  307,  260,  188,  188,   19,  188,  121,
      301,  302,  303,  301,  302,  303,  304,  241,  263,  304,
      241,  263,  307,  301,  302,  303,  307,  307,  307,  304,
      241,  263,  244,  123,  244,   84,  305,  256,  306,  305,
      256,  306,  241,  256,  264,  241,  256,  264,  307,  305,
      256,  306,  307,  307,  307,  241,  256,  264,  132,  132,
      132,  132,  307,  307,  307,  260,  307,   94,  260,  307,
      307,  307,  307,  188,  188,   19,  188,  145,  260,  307,
      307,  307,  307,  307,  307,  307,  273,  307,  307,  273,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  273,

      258,  147,  258,  117,  307,  307,  307,  307,  307,  307,
      307,  307,  274,  307,  307,  274,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  274,  188,  188,   19,  188,
      149,  307,  307,  307,  307,  307,  307,  307,  307,  276,
      307,  307,  276,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  276,  262,  151,  262,  121,  307,  307,  307,
      307,  307,  307,  223,  307,  277,  307,  307,  277,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  277,  185,
      185,  185,  185,  307,  307,  307,  307,  307,  174,  307,
      307,  307,  307,  307,  272,  171,  272,  145,  307,  307,

      307,  307,  307,  307,  307,  307,  283,  307,  307,  283,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  283,
      275,  177,  275,  149,  307,  307,  307,  307,  307,  307,
      307,  307,  285,  307,  307,  285,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  285,  201,  201,  201,  201,
      307,  307,  307,  307,  307,  180,  307,  307,  307,  307,
      307,   18,   18,   18,   18,   18,   18,   22,   22,   22,
       22,   22,   22,   30,   30,   30,   30,   30,   30,   31,
       31,   31,   31,   31,   31,   33,   33,   33,   33,   33,
       33,   37,   37,   37,   37,   37,   37,   46,   46,   46,

       46,   46,   46,   49,   49,   49,   49,   49,   49,   55,
       55,   55,   55,   55,   55,   62,   62,   62,   62,   62,
       62,   64,   64,   64,   64,   64,   64,   67,   67,   67,
       67,   67,   67,   73,   73,   73,   73,   73,   73,   76,
       76,   76,   76,   76,   76,   84,   84,   84,   84,   84,
       84,   94,   94,  307,   94,   99,   99,   99,   99,   99,
       99,  102,  102,  102,  102,  102,  102,  111,  111,  111,
      111,  111,  111,  117,  117,  117,  117,  117,  117,  121,
      121,  121,  121,  121,  121,  128,  128,  128,  128,  128,
      128,  132,  132,  132,  132,  132,  137,  137,  137,  137,

      137,  137,  145,  145,  145,  145,  145,  145,  149,  149,
      149,  149,  149,  149,  155,  155,  155,  155,  163,  163,
      163,  163,  163,  174,  307,  174,  174,  180,  307,  180,
      182,  182,  182,  182,  182,  185,  185,  185,  185,  185,
      195,  195,  195,  195,  195,  201,  201,  201,  201,  201,
      210,  210,  210,  210,  210,  210,  226,  226,  226,  226,
      226,  226,  244,  244,  244,  244,  244,  244,  258,  258,
      258,  258,  258,  258,  262,  262,  262,  262,  262,  262,
      272,  272,  272,  272,  272,  272,  275,  275,  275,  275,
      275,  275,    3,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307
    } ;

static yyconst flex_int16_t yy_chk[1627] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    7,    8,    7,    2,   21,   44,
       21,   44,    8,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,   10,   11,   14,   15,
       16,  336,   36,   33,   16,   10,   11,   13,   13,   13,
       13,   17,   22,   19,   30,   24,   35,   17,   19,   22,

       13,   14,   24,   13,   23,   23,   33,   28,   15,   89,
       23,   36,   89,   13,   26,   28,   30,   29,   43,   35,
       50,   50,   26,   43,   28,   26,   50,   29,   26,   26,
       26,   26,   26,   26,  330,   26,   29,  262,   26,   26,
       26,   26,   26,   88,   26,   27,   27,   27,   27,   34,
       40,   38,   41,   88,   34,   38,   40,   40,   27,   49,
       41,   27,  241,   51,   34,   41,   49,   64,  226,   48,
       51,   27,   32,   32,   32,   32,   48,   48,   58,   66,
       61,   67,   48,   61,   32,   57,   58,   32,   57,  154,
       64,   59,   72,   61,   57,   58,   59,   32,   52,   72,

      154,   52,   66,   57,   52,   52,   52,   52,   52,   52,
       67,   52,   76,   59,   52,   52,   52,   52,   52,   76,
       52,   53,   69,   53,   53,   68,   69,   53,   53,   53,
       53,   53,   53,  207,   53,  198,  182,   53,   53,   53,
       53,   53,   63,   53,   54,   54,   54,   54,   60,   60,
       63,   65,  173,   60,   68,   63,   65,   54,   77,   77,
       54,   60,   94,   91,   77,   63,   65,   94,   78,   75,
       54,   56,   56,   56,   56,   78,   75,   75,  169,   86,
       86,   56,   75,   56,   86,   91,   56,  110,   87,  106,
      168,   87,   86,  106,  110,  105,   56,   79,   79,  167,

       79,   87,  155,   79,   79,   79,   79,   79,   79,   90,
       79,   98,   90,   79,   79,   79,   79,   79,   90,   79,
       80,   80,   80,   80,  105,   95,   96,   90,   95,   96,
      103,  127,  144,   80,   98,  103,   80,  114,   95,   96,
      143,  127,  142,  132,  114,  103,   80,   82,  132,  139,
       82,  102,  104,   82,   82,   82,   82,   82,   82,  137,
       82,  135,  125,   82,   82,   82,   82,   82,  100,   82,
       83,   83,   83,   83,  102,  104,  100,  113,  121,  124,
      136,  100,  124,   83,  113,  113,   83,  112,  128,  129,
      113,  100,  124,  111,  128,  129,   83,   85,   85,   85,

       85,  126,  141,  136,  126,  131,  141,  109,  131,   85,
      128,  129,   85,  107,  126,  130,  130,  134,  131,  130,
      134,  138,   85,  116,  116,  116,  116,  130,  101,  138,
      134,  140,  180,  147,  138,  147,  116,  158,  147,  116,
      158,   99,  148,  180,  138,  148,  147,   97,  158,  116,
      118,  118,  118,  118,  140,  148,  151,  151,  153,   93,
      152,  151,  118,  152,  162,  118,  153,  153,   92,  156,
      162,  153,  156,  152,   81,  118,  120,  120,  120,  120,
      157,  159,  156,  157,  159,  160,  162,  165,  160,  120,
      165,   74,  120,  157,  159,   73,  166,   71,  160,  166,

      165,   62,  120,  122,  122,  122,  122,  172,   55,  166,
      172,  174,  171,  122,  171,  122,  174,  171,  122,  175,
      172,   46,  175,  176,   45,  171,  176,   42,  122,  123,
      123,  123,  175,   39,  123,  177,  176,  177,  178,   37,
      177,  178,  123,  133,  133,  133,  133,  179,  177,  185,
      179,  178,  133,  181,  185,  133,  181,  133,  133,   25,
      179,  184,  187,   20,  184,  187,  181,   18,  133,  146,
      146,  146,  146,  191,  184,  187,  191,  192,  195,  193,
      192,  146,  193,  195,  146,   12,  191,    6,  194,    5,
      192,  194,  193,    4,  146,  150,  150,  150,  150,  197,

      199,  194,  197,  199,  201,  200,    3,  150,  200,  201,
      150,    0,  197,  199,  267,  267,  267,  267,  200,    0,
      150,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  164,  164,  164,  164,  203,  204,
      205,  203,  204,  205,  206,  212,  164,  206,  212,  164,
        0,  203,  204,  205,    0,    0,    0,  206,  212,  164,
      183,  183,  183,  183,  213,  214,  215,  213,  214,  215,
      183,  216,  183,    0,  216,  183,    0,  213,  214,  215,

      217,    0,    0,  217,  216,  183,  186,  186,  186,  186,
        0,  218,    0,  217,  218,  186,  219,    0,  186,  219,
      186,  186,    0,  220,  218,    0,  220,    0,    0,  219,
        0,  186,  188,    0,  221,  188,  220,  221,  188,  188,
      188,  188,  188,  188,    0,  188,    0,  221,  188,  188,
      188,  188,  188,    0,  188,  189,  189,  222,  189,    0,
      222,  189,  189,  189,  189,  189,  189,    0,  189,    0,
      222,  189,  189,  189,  189,  189,    0,  189,  190,  190,
      190,  190,  190,  228,  229,  230,  228,  229,  230,  231,
      232,  190,  231,  232,  190,    0,  228,  229,  230,    0,

        0,    0,  231,  232,  190,  196,  196,  196,  196,  233,
      234,  235,  233,  234,  235,  236,  237,  196,  236,  237,
      196,    0,  233,  234,  235,    0,    0,    0,  236,  237,
      196,  202,  202,  202,  202,  238,  246,    0,  238,  246,
      202,  247,    0,  202,  247,  202,  202,    0,  238,  246,
        0,    0,    0,    0,  247,    0,  202,  208,  248,  250,
      208,  248,  250,  208,  208,  208,  208,  208,  208,    0,
      208,  248,  250,  208,  208,  208,  208,  208,    0,  208,
      209,  209,  209,  209,  209,  251,  252,  253,  251,  252,
      253,  254,  255,  209,  254,  255,  209,    0,  251,  252,

      253,    0,    0,    0,  254,  255,  209,  211,  211,  211,
      211,  264,  265,  266,  264,  265,  266,  268,  269,  211,
      268,  269,  211,    0,  264,  265,  266,    0,    0,    0,
      268,  269,  211,  223,  270,  274,  223,  270,  274,  223,
      223,  223,  223,  223,  223,    0,  223,  270,  274,  223,
      223,  223,  223,  223,    0,  223,  224,  277,  224,  224,
      277,    0,  224,  224,  224,  224,  224,  224,    0,  224,
      277,    0,  224,  224,  224,  224,  224,    0,  224,  225,
      225,  225,  225,  225,  278,  279,  280,  278,  279,  280,
      281,  283,  225,  281,  283,  225,    0,  278,  279,  280,

        0,    0,    0,  281,  283,  225,  227,  227,  227,  227,
      284,  285,  286,  284,  285,  286,  227,  287,  227,    0,
      287,  227,    0,  284,  285,  286,    0,    0,    0,    0,
      287,  227,  239,  239,  288,  239,    0,  288,  239,  239,
      239,  239,  239,  239,    0,  239,    0,  288,  239,  239,
      239,  239,  239,    0,  239,  240,  240,  240,  240,  240,
      289,  290,  291,  289,  290,  291,  292,  293,  240,  292,
      293,  240,    0,  289,  290,  291,    0,    0,    0,  292,
      293,  240,  242,  294,  295,  242,  294,  295,  242,  242,
      242,  242,  242,  242,    0,  242,  294,  295,  242,  242,

      242,  242,  242,    0,  242,  243,  243,  243,  243,  243,
      296,  297,  298,  296,  297,  298,  299,  300,  243,  299,
      300,  243,    0,  296,  297,  298,    0,    0,    0,  299,
      300,  243,  245,  245,  245,  245,  301,  302,  303,  301,
      302,  303,  304,  305,  245,  304,  305,  245,    0,  301,
      302,  303,    0,    0,    0,  304,  305,  245,  249,  249,
      249,  249,    0,    0,    0,  306,    0,  249,  306,    0,
        0,    0,  249,  257,  257,  257,  257,  257,  306,    0,
        0,    0,    0,    0,    0,    0,  257,    0,    0,  257,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  257,

      259,  259,  259,  259,    0,    0,    0,    0,    0,    0,
        0,    0,  259,    0,    0,  259,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  259,  261,  261,  261,  261,
      261,    0,    0,    0,    0,    0,    0,    0,    0,  261,
        0,    0,  261,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  261,  263,  263,  263,  263,    0,    0,    0,
        0,    0,    0,  263,    0,  263,    0,    0,  263,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  263,  271,
      271,  271,  271,    0,    0,    0,    0,    0,  271,    0,
        0,    0,    0,  271,  273,  273,  273,  273,    0,    0,

        0,    0,    0,    0,    0,    0,  273,    0,    0,  273,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  273,
      276,  276,  276,  276,    0,    0,    0,    0,    0,    0,
        0,    0,  276,    0,    0,  276,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  276,  282,  282,  282,  282,
        0,    0,    0,    0,    0,  282,    0,    0,    0,    0,
      282,  308,  308,  308,  308,  308,  308,  309,  309,  309,
      309,  309,  309,  310,  310,  310,  310,  310,  310,  311,
      311,  311,  311,  311,  311,  312,  312,  312,  312,  312,
      312,  313,  313,  313,  313,  313,  313,  314,  314,  314,

      314,  314,  314,  315,  315,  315,  315,  315,  315,  316,
      316,  316,  316,  316,  316,  317,  317,  317,  317,  317,
      317,  318,  318,  318,  318,  318,  318,  319,  319,  319,
      319,  319,  319,  320,  320,  320,  320,  320,  320,  321,
      321,  321,  321,  321,  321,  322,  322,  322,  322,  322,
      322,  323,  323,    0,  323,  324,  324,  324,  324,  324,
      324,  325,  325,  325,  325,  325,  325,  326,  326,  326,
      326,  326,  326,  327,  327,  327,  327,  327,  327,  328,
      328,  328,  328,  328,  328,  329,  329,  329,  329,  329,
      329,  331,  331,  331,  331,  331,  332,  332,  332,  332,

      332,  332,  333,  333,  333,  333,  333,  333,  334,  334,
      334,  334,  334,  334,  335,  335,  335,  335,  337,  337,
      337,  337,  337,  338,    0,  338,  338,  339,    0,  339,
      340,  340,  340,  340,  340,  341,  341,  341,  341,  341,
      342,  342,  342,  342,  342,  343,  343,  343,  343,  343,
      344,  344,  344,  344,  344,  344,  345,  345,  345,  345,
      345,  345,  346,  346,  346,  346,  346,  346,  347,  347,
      347,  347,  347,  347,  348,  348,  348,  348,  348,  348,
      349,  349,  349,  349,  349,  349,  350,  350,  350,  350,
      350,  350,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "markdown.grammar"
#line 895 "lex.markdown.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

int markdownlex_init (yyscan_t* scanner);

int markdownlex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int markdownlex_destroy (yyscan_t yyscanner );

int markdownget_debug (yyscan_t yyscanner );

void markdownset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE markdownget_extra (yyscan_t yyscanner );

void markdownset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *markdownget_in (yyscan_t yyscanner );

void markdownset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *markdownget_out (yyscan_t yyscanner );

void markdownset_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t markdownget_leng (yyscan_t yyscanner );

char *markdownget_text (yyscan_t yyscanner );

int markdownget_lineno (yyscan_t yyscanner );

void markdownset_lineno (int line_number ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int markdownwrap (yyscan_t yyscanner );
#else
extern int markdownwrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int markdownlex (yyscan_t yyscanner);

#define YY_DECL int markdownlex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 37 "markdown.grammar"


#line 1120 "lex.markdown.c"

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			markdownensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				markdown_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		markdown_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 308 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1593 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 39 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNEM, yyscanner);}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 40 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNSTRONG, yyscanner);}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 41 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNSTRONGEM, yyscanner);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNSTRIKETHROUGH, yyscanner);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 43 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNHEADER, yyscanner);}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 44 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNMULTILINEHEADER, yyscanner);}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 45 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNURL, yyscanner);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNHREF, yyscanner);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNBULLETSTART, yyscanner);}
	YY_BREAK
case 10:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 49 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNNEWLINE, yyscanner);}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 50 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNPARAGRAPH, yyscanner);}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 51 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNUNKNOWN, yyscanner);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 "markdown.grammar"
{markdownConsume(yytext, MARKDOWNUNKNOWN, yyscanner);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "markdown.grammar"
ECHO;
	YY_BREAK
#line 1284 "lex.markdown.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * markdownlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( markdownwrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of markdownlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					markdownrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			markdownrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) markdownrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 308 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 308 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 307);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					markdownrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( markdownwrap(yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void markdownrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        markdownensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            markdown_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	markdown_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	markdown_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void markdown_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		markdownpop_buffer_state();
	 *		markdownpush_buffer_state(new_buffer);
     */
	markdownensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	markdown_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (markdownwrap()) processing, but the only time this flag
	 * is looked at is after markdownwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void markdown_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE markdown_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) markdownalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in markdown_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) markdownalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in markdown_create_buffer()" );

	b->yy_is_our_buffer = 1;

	markdown_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with markdown_create_buffer()
 * @param yyscanner The scanner object.
 */
    void markdown_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		markdownfree((void *) b->yy_ch_buf ,yyscanner );

	markdownfree((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a markdownrestart() or at EOF.
 */
    static void markdown_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	markdown_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then markdown_init_buffer was _probably_
     * called from markdownrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void markdown_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		markdown_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void markdownpush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	markdownensure_buffer_stack(yyscanner);

	/* This block is copied from markdown_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from markdown_switch_to_buffer. */
	markdown_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void markdownpop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	markdown_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		markdown_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void markdownensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)markdownalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in markdownensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)markdownrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in markdownensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE markdown_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) markdownalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in markdown_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	markdown_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to markdownlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       markdown_scan_bytes() instead.
 */
YY_BUFFER_STATE markdown_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return markdown_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to markdownlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE markdown_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) markdownalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in markdown_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = markdown_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in markdown_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE markdownget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int markdownget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int markdownget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *markdownget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *markdownget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t markdownget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *markdownget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void markdownset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void markdownset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "markdownset_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void markdownset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "markdownset_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see markdown_switch_to_buffer
 */
void markdownset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void markdownset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int markdownget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void markdownset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* markdownlex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int markdownlex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) markdownalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* markdownlex_init_extra has the same functionality as markdownlex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to markdownalloc in
 * the yyextra field.
 */

int markdownlex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    markdownset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) markdownalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    markdownset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from markdownlex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * markdownlex_init()
     */
    return 0;
}

/* markdownlex_destroy is for both reentrant and non-reentrant scanners. */
int markdownlex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		markdown_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		markdownpop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	markdownfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        markdownfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * markdownlex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    markdownfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *markdownalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *markdownrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void markdownfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see markdownrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 54 "markdown.grammar"



int markdownwrap(yyscan_t yyscanner){return 1;}

