//
// Copyright 2012 Jeff Verkoeyen
//
// Autogenerated by flex using Jeff Verkoeyen's Markdown grammar
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#include "MarkdownTokens.h"

#line 3 "lex.markdown.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer markdown_create_buffer
#define yy_delete_buffer markdown_delete_buffer
#define yy_flex_debug markdown_flex_debug
#define yy_init_buffer markdown_init_buffer
#define yy_flush_buffer markdown_flush_buffer
#define yy_load_buffer_state markdown_load_buffer_state
#define yy_switch_to_buffer markdown_switch_to_buffer
#define yyin markdownin
#define yyleng markdownleng
#define yylex markdownlex
#define yylineno markdownlineno
#define yyout markdownout
#define yyrestart markdownrestart
#define yytext markdowntext
#define yywrap markdownwrap
#define yyalloc markdownalloc
#define yyrealloc markdownrealloc
#define yyfree markdownfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE markdownrestart(markdownin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t markdownleng;

extern FILE *markdownin, *markdownout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up markdowntext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up markdowntext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via markdownrestart()), so that the user can continue scanning by
	 * just pointing markdownin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when markdowntext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t markdownleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow markdownwrap()'s to do buffer switches
 * instead of setting up a fresh markdownin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void markdownrestart (FILE *input_file  );
void markdown_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE markdown_create_buffer (FILE *file,int size  );
void markdown_delete_buffer (YY_BUFFER_STATE b  );
void markdown_flush_buffer (YY_BUFFER_STATE b  );
void markdownpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void markdownpop_buffer_state (void );

static void markdownensure_buffer_stack (void );
static void markdown_load_buffer_state (void );
static void markdown_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER markdown_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE markdown_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE markdown_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE markdown_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *markdownalloc (yy_size_t  );
void *markdownrealloc (void *,yy_size_t  );
void markdownfree (void *  );

#define yy_new_buffer markdown_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        markdownensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            markdown_create_buffer(markdownin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        markdownensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            markdown_create_buffer(markdownin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *markdownin = (FILE *) 0, *markdownout = (FILE *) 0;

typedef int yy_state_type;

extern int markdownlineno;

int markdownlineno = 1;

extern char *markdowntext;
#define yytext_ptr markdowntext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up markdowntext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	markdownleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 8
#define YY_END_OF_BUFFER 9
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[183] =
    {   0,
        0,    0,    9,    7,    6,    6,    4,    7,    7,    7,
        7,    7,    7,    6,    4,    4,    0,    1,    0,    0,
        0,    0,    0,    0,    0,    0,    1,    4,    1,    0,
        0,    0,    5,    0,    0,    0,    0,    0,    0,    0,
        0,    4,    0,    0,    2,    5,    0,    5,    5,    0,
        5,    5,    0,    0,    0,    0,    0,    0,    0,    2,
        4,    2,    0,    0,    5,    0,    5,    5,    5,    0,
        5,    5,    5,    0,    0,    0,    0,    0,    4,    3,
        5,    5,    5,    5,    5,    5,    5,    0,    0,    0,
        5,    5,    5,    5,    5,    0,    5,    5,    5,    0,

        5,    5,    5,    5,    5,    0,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    5,    6,    5,    5,    5,    5,    5,
        5,    7,    5,    5,    8,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,    5,    5,
        5,    5,    5,    5,   11,   11,   11,   11,   11,   13,
        8,   14,    8,    8,    8,    8,    8,    8,    8,   15,
        8,    8,   16,   17,    8,    8,    8,    8,    8,    8,
        5,   18,    5,    5,   19,    5,   11,   11,   11,   11,

       11,   20,    8,   21,    8,    8,    8,    8,    8,    8,
        8,   22,    8,    8,   23,   24,    8,    8,    8,    8,
        8,    8,    5,    5,    5,    5,    1,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,

       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25
    } ;

static yyconst flex_int32_t yy_meta[26] =
    {   0,
        1,    1,    2,    3,    4,    4,    4,    5,    6,    7,
        5,    4,    5,    5,    5,    5,    5,    5,    4,    5,
        5,    5,    5,    5,    5
    } ;

static yyconst flex_int16_t yy_base[211] =
    {   0,
        0,    0,  329,  926,   24,   27,  313,  304,   23,   33,
       16,   23,  257,   35,    0,  269,  266,  264,   26,  251,
       34,   49,   39,   29,   70,  246,  245,  255,  926,  219,
      214,  201,   50,   64,   38,   93,  102,   54,   69,  196,
      178,  188,  167,  160,  157,   60,   80,   89,   91,   92,
      106,  125,   97,  150,   63,    0,  110,  138,  125,  118,
      126,  926,  115,  113,  121,  129,  123,  148,  136,  142,
      138,  167,  152,  162,  101,  166,   73,   69,    0,  926,
      171,  188,  182,  178,  207,  187,  192,  193,  227,  203,
      211,  242,  243,  246,  247,  257,    0,  277,  302,  321,

      261,  296,  297,  301,  307,  315,   76,  345,  370,    0,
      389,  319,  320,  323,  364,  408,  426,  451,  476,   57,
      495,  365,  369,  514,  375,  383,  532,  557,   56,  577,
      602,    0,  621,  386,  394,  181,  640,    0,  658,    0,
      677,    0,  697,   52,  716,  402,  410,  470,    0,  735,
      471,    0,  754,  475,  481,  489,  492,  500,  508,  516,
      551,  552,  556,  596,  597,  601,  607,  615,  618,  626,
      634,  644,  652,  655,  663,  671,  674,  682,  692,  693,
      696,  926,  774,  781,  784,  788,  795,  802,   47,  807,
      814,  821,   44,  824,  829,  836,  839,  844,  847,  852,

      857,  862,  869,  876,  883,  890,  897,  904,  911,  918
    } ;

static yyconst flex_int16_t yy_def[211] =
    {   0,
      182,    1,  182,  182,  182,  182,  183,  184,  185,  185,
       10,  186,  187,  182,  183,  183,  184,  188,  185,  189,
      190,  185,   10,   10,   10,  187,  191,  183,  182,  188,
      192,  193,  194,  195,   23,   25,   23,   22,   25,  191,
      196,  183,  182,  192,  182,  197,  198,  194,  199,  200,
      194,  194,   36,  182,   37,   37,   25,  182,  196,  182,
      183,  182,  182,  182,  197,  201,  197,  197,  199,  202,
      194,   52,   52,   36,  182,   25,  182,  182,  183,  182,
      197,   68,   68,  199,  199,   72,   52,   36,  182,   25,
       82,   68,   85,   72,   52,   36,  203,  182,  204,   10,

       82,   68,   85,   72,   52,   36,   98,  182,  205,   98,
       98,   82,   68,   85,   72,  194,  182,  182,  206,   98,
       98,  111,   82,  197,   85,   72,  182,  207,  118,  182,
      208,  118,  118,  121,  111,  124,  199,  127,  209,  127,
      127,  130,  210,  118,  118,  133,  121,  111,  127,  127,
      141,  130,  130,  145,  133,  121,  111,  150,  141,  153,
      145,  133,  121,  111,  150,  141,  153,  145,  133,  121,
      150,  141,  153,  145,  133,  150,  141,  153,  145,  150,
      153,    0,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,

      182,  182,  182,  182,  182,  182,  182,  182,  182,  182
    } ;

static yyconst flex_int16_t yy_nxt[952] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,    4,    4,
        9,    4,   10,   11,    9,    9,    9,   12,   13,   10,
       11,    9,    9,    9,    9,   14,   14,   14,   14,   14,
       14,   20,   23,   25,   32,   25,   14,   14,   14,   23,
       21,   20,   25,   21,   36,   19,   36,   32,   46,   22,
       21,   33,   19,   36,   19,   38,   22,   32,   20,   49,
      117,   19,   38,   37,  117,  117,   21,   50,   56,   49,
       37,   24,   24,   24,   52,   56,   52,   66,   19,   57,
       39,   57,   39,   52,  117,   19,   19,   80,   57,   39,
       68,   78,   68,   19,   35,   35,   35,   32,   49,   68,

       49,   32,   72,   53,   72,   53,   50,   74,   70,   74,
       89,   72,   53,   54,   20,   49,   74,   55,   19,   80,
       76,   64,   76,   50,   55,   19,   51,   51,   51,   76,
       49,   79,   49,   20,   49,   73,   78,   73,   66,   82,
       66,   82,   50,   77,   73,   49,   32,   49,   82,   67,
       67,   67,   85,   70,   85,   50,   62,   49,   83,   75,
       83,   85,   87,   64,   87,   66,   63,   83,   71,   71,
       71,   87,   88,   62,   88,   32,   90,   86,   90,   86,
       49,   88,   81,   81,   81,   90,   86,   49,   66,   81,
       81,   81,   92,   61,   92,   70,   60,   94,   91,   94,

       91,   92,   95,   96,   95,   96,   94,   91,   84,   84,
       84,   95,   96,  100,   58,  100,   49,   93,   47,   93,
       45,  101,  100,  101,   70,   43,   93,   97,   97,   97,
      101,   97,   97,   97,   98,   97,   97,   98,   97,   98,
       98,   98,   98,   98,   99,   97,   98,   98,   98,   98,
       98,   98,  102,  103,  102,  103,  104,  105,  104,  105,
       42,  102,  103,   41,   29,  104,  105,  106,   34,  106,
       31,  112,   29,  112,   28,   27,  106,   97,   97,   97,
      112,   97,   97,   97,  107,  108,   97,  107,   97,  107,
      107,  107,  107,  107,  109,   97,  107,  107,  107,  107,

      107,  107,   97,   97,   97,   24,  113,  114,  113,  114,
       18,  115,  111,  115,  111,  113,  114,  116,   16,  116,
      115,  111,   24,   24,   24,   19,  116,   19,  182,  123,
      124,  123,  124,  125,   19,  125,  182,   19,  123,  124,
      182,  182,  125,  182,   19,   97,   97,   97,  182,   97,
       97,   97,  118,   97,   97,  118,   97,  118,  118,  118,
      118,  118,  119,   97,  118,  118,  118,  118,  118,  118,
       97,   97,   97,   35,  126,  135,  126,  135,  182,  136,
      121,  136,  121,  126,  135,  137,  182,  137,  136,  121,
      110,  110,   24,   48,  137,   48,  147,  182,  147,  122,

      182,  122,   48,  182,  148,  147,  148,  182,  122,   51,
       51,   51,  155,  148,  155,  182,   20,   49,  182,  182,
      156,  155,  156,  182,  182,   50,   97,   97,   97,  156,
       97,   97,   97,  127,   97,   97,  127,   97,  127,  127,
      127,  127,  127,  128,   97,  127,  127,  127,  127,  127,
      127,   97,   97,   97,  182,   97,   97,   97,  129,  108,
      130,  129,   97,  129,  129,  129,  129,  129,  131,   97,
      129,  129,  129,  129,  129,  129,   97,   97,   97,   51,
      157,  159,  157,  159,  182,  161,  133,  161,  133,  157,
      159,  162,  182,  162,  161,  133,  120,  120,   35,  163,

      162,  163,  164,  117,  164,  134,  182,  134,  163,  182,
      165,  164,  165,  182,  134,   67,   67,   67,  166,  165,
      166,  182,  182,   49,  182,  182,  167,  166,  167,  182,
      182,   66,   97,   97,   97,  167,   97,   97,   97,  138,
       97,  130,  138,   97,  138,  138,  138,  138,  138,  139,
       97,  138,  138,  138,  138,  138,  138,   97,   97,   97,
       67,  168,  169,  168,  169,  182,  170,  141,  170,  141,
      168,  169,  182,  182,  182,  170,  141,   97,   97,   97,
      182,   97,   97,   97,  142,   97,  130,  142,   97,  142,
      142,  142,  142,  142,  143,   97,  142,  142,  142,  142,

      142,  142,   97,   97,   97,   71,  107,  171,  107,  171,
      182,  172,  145,  172,  145,  107,  171,  173,  182,  173,
      172,  145,  132,  132,   51,  174,  173,  174,  175,  182,
      175,  146,  182,  146,  174,  182,  107,  175,  107,  182,
      146,   84,   84,   84,  176,  107,  176,  182,  182,   49,
      182,  182,  182,  176,  177,  182,  177,   70,   97,   97,
       97,   81,  178,  177,  178,  179,  182,  179,  150,  182,
      150,  178,  182,  129,  179,  129,  182,  150,  140,  140,
       67,  180,  129,  180,  138,  182,  138,  151,  182,  151,
      180,  182,  181,  138,  181,  182,  151,   97,   97,   97,

       84,  181,  129,  138,  129,  138,  142,  153,  142,  153,
      182,  129,  138,  182,  182,  142,  153,  144,  144,   71,
      182,  182,  182,  182,  117,  182,  154,  182,  154,  182,
      182,  182,  182,  182,  182,  154,  149,  149,   81,  182,
      182,  182,  182,  182,  182,  158,  182,  158,  182,  182,
      182,  182,  182,  182,  158,  152,  152,   84,  182,  182,
      182,  182,  182,  182,  160,  182,  160,  182,  182,  182,
      182,  182,  182,  160,   15,  182,   15,   15,   15,   15,
       15,   17,   17,   17,   17,   17,   17,   17,   19,   19,
       24,   24,   24,   24,   24,   26,   26,   26,   26,   26,

       26,   26,   30,   30,   30,   30,   30,   30,   30,   35,
       35,   35,   35,   35,   40,   40,   40,   40,   40,   40,
       40,   44,   44,   44,   44,   44,   44,   44,   48,   48,
       48,   51,   51,   51,   51,   51,   59,   59,   59,   59,
       59,   59,   59,   65,  182,   65,   67,   67,   67,   67,
       67,   69,  182,   69,   71,   71,   71,   71,   71,   81,
       81,   81,   81,   81,   84,   84,   84,   84,   84,   97,
       97,  182,   97,   97,   97,   97,  110,  110,  110,  110,
      110,  110,  110,  120,  120,  120,  120,  120,  120,  120,
      132,  132,  132,  132,  132,  132,  132,  140,  140,  140,

      140,  140,  140,  140,  144,  144,  144,  144,  144,  144,
      144,  149,  149,  149,  149,  149,  149,  149,  152,  152,
      152,  152,  152,  152,  152,    3,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182
    } ;

static yyconst flex_int16_t yy_chk[952] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    6,    6,
        6,    9,   11,   12,   19,   12,   14,   14,   14,   11,
        9,   10,   12,   19,   21,   24,   21,   23,  193,   10,
       10,  189,   24,   21,   35,   23,   10,   22,   33,   33,
      144,   35,   23,   22,  129,  120,   22,   33,   38,   46,
       22,   25,   25,   25,   34,   38,   34,   46,   55,   39,
       25,   39,   25,   34,  107,   55,   25,   78,   39,   25,
       47,   77,   47,   25,   36,   36,   36,   48,   48,   47,

       49,   36,   50,   36,   50,   36,   48,   53,   49,   53,
       75,   50,   36,   37,   51,   51,   53,   37,   37,   64,
       57,   63,   57,   51,   37,   37,   52,   52,   52,   57,
       65,   61,   67,   52,   52,   52,   60,   52,   65,   66,
       67,   66,   52,   59,   52,   69,   71,   71,   66,   68,
       68,   68,   70,   69,   70,   71,   58,   68,   68,   54,
       68,   70,   73,   45,   73,   68,   44,   68,   72,   72,
       72,   73,   74,   43,   74,   72,   76,   72,   76,   72,
       81,   74,  136,  136,  136,   76,   72,   84,   81,   82,
       82,   82,   83,   42,   83,   84,   41,   86,   82,   86,

       82,   83,   87,   88,   87,   88,   86,   82,   85,   85,
       85,   87,   88,   90,   40,   90,   85,   85,   32,   85,
       31,   91,   90,   91,   85,   30,   85,   89,   89,   89,
       91,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   92,   93,   92,   93,   94,   95,   94,   95,
       28,   92,   93,   27,   26,   94,   95,   96,   20,   96,
       18,  101,   17,  101,   16,   13,   96,   98,   98,   98,
      101,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,

       98,   98,   99,   99,   99,   99,  102,  103,  102,  103,
        8,  104,   99,  104,   99,  102,  103,  105,    7,  105,
      104,   99,  100,  100,  100,  106,  105,  106,    3,  112,
      113,  112,  113,  114,  106,  114,    0,  100,  112,  113,
        0,    0,  114,    0,  100,  108,  108,  108,    0,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      109,  109,  109,  109,  115,  122,  115,  122,    0,  123,
      109,  123,  109,  115,  122,  125,    0,  125,  123,  109,
      111,  111,  111,  126,  125,  126,  134,    0,  134,  111,

        0,  111,  126,    0,  135,  134,  135,    0,  111,  116,
      116,  116,  146,  135,  146,    0,  116,  116,    0,    0,
      147,  146,  147,    0,    0,  116,  117,  117,  117,  147,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      117,  118,  118,  118,    0,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  119,  119,  119,  119,
      148,  151,  148,  151,    0,  154,  119,  154,  119,  148,
      151,  155,    0,  155,  154,  119,  121,  121,  121,  156,

      155,  156,  157,  121,  157,  121,    0,  121,  156,    0,
      158,  157,  158,    0,  121,  124,  124,  124,  159,  158,
      159,    0,    0,  124,    0,    0,  160,  159,  160,    0,
        0,  124,  127,  127,  127,  160,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  128,  128,  128,
      128,  161,  162,  161,  162,    0,  163,  128,  163,  128,
      161,  162,    0,    0,    0,  163,  128,  130,  130,  130,
        0,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,

      130,  130,  131,  131,  131,  131,  164,  165,  164,  165,
        0,  166,  131,  166,  131,  164,  165,  167,    0,  167,
      166,  131,  133,  133,  133,  168,  167,  168,  169,    0,
      169,  133,    0,  133,  168,    0,  170,  169,  170,    0,
      133,  137,  137,  137,  171,  170,  171,    0,    0,  137,
        0,    0,    0,  171,  172,    0,  172,  137,  139,  139,
      139,  139,  173,  172,  173,  174,    0,  174,  139,    0,
      139,  173,    0,  175,  174,  175,    0,  139,  141,  141,
      141,  176,  175,  176,  177,    0,  177,  141,    0,  141,
      176,    0,  178,  177,  178,    0,  141,  143,  143,  143,

      143,  178,  179,  180,  179,  180,  181,  143,  181,  143,
        0,  179,  180,    0,    0,  181,  143,  145,  145,  145,
        0,    0,    0,    0,  145,    0,  145,    0,  145,    0,
        0,    0,    0,    0,    0,  145,  150,  150,  150,    0,
        0,    0,    0,    0,    0,  150,    0,  150,    0,    0,
        0,    0,    0,    0,  150,  153,  153,  153,    0,    0,
        0,    0,    0,    0,  153,    0,  153,    0,    0,    0,
        0,    0,    0,  153,  183,    0,  183,  183,  183,  183,
      183,  184,  184,  184,  184,  184,  184,  184,  185,  185,
      186,  186,  186,  186,  186,  187,  187,  187,  187,  187,

      187,  187,  188,  188,  188,  188,  188,  188,  188,  190,
      190,  190,  190,  190,  191,  191,  191,  191,  191,  191,
      191,  192,  192,  192,  192,  192,  192,  192,  194,  194,
      194,  195,  195,  195,  195,  195,  196,  196,  196,  196,
      196,  196,  196,  197,    0,  197,  198,  198,  198,  198,
      198,  199,    0,  199,  200,  200,  200,  200,  200,  201,
      201,  201,  201,  201,  202,  202,  202,  202,  202,  203,
      203,    0,  203,  203,  203,  203,  204,  204,  204,  204,
      204,  204,  204,  205,  205,  205,  205,  205,  205,  205,
      206,  206,  206,  206,  206,  206,  206,  207,  207,  207,

      207,  207,  207,  207,  208,  208,  208,  208,  208,  208,
      208,  209,  209,  209,  209,  209,  209,  209,  210,  210,
      210,  210,  210,  210,  210,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int markdown_flex_debug;
int markdown_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *markdowntext;
#line 1 "markdown.grammar"
#line 742 "lex.markdown.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int markdownlex_destroy (void );

int markdownget_debug (void );

void markdownset_debug (int debug_flag  );

YY_EXTRA_TYPE markdownget_extra (void );

void markdownset_extra (YY_EXTRA_TYPE user_defined  );

FILE *markdownget_in (void );

void markdownset_in  (FILE * in_str  );

FILE *markdownget_out (void );

void markdownset_out  (FILE * out_str  );

yy_size_t markdownget_leng (void );

char *markdownget_text (void );

int markdownget_lineno (void );

void markdownset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int markdownwrap (void );
#else
extern int markdownwrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( markdowntext, markdownleng, 1, markdownout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( markdownin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( markdownin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, markdownin))==0 && ferror(markdownin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(markdownin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int markdownlex (void);

#define YY_DECL int markdownlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after markdowntext and markdownleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 31 "markdown.grammar"


#line 925 "lex.markdown.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! markdownin )
			markdownin = stdin;

		if ( ! markdownout )
			markdownout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			markdownensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				markdown_create_buffer(markdownin,YY_BUF_SIZE );
		}

		markdown_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of markdowntext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 183 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 926 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 33 "markdown.grammar"
{markdownConsume(markdowntext, MARKDOWNEM);}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 34 "markdown.grammar"
{markdownConsume(markdowntext, MARKDOWNSTRONG);}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 35 "markdown.grammar"
{markdownConsume(markdowntext, MARKDOWNSTRONGEM);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 36 "markdown.grammar"
{markdownConsume(markdowntext, MARKDOWNHEADER);}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 37 "markdown.grammar"
{markdownConsume(markdowntext, MARKDOWNURL);}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 39 "markdown.grammar"
{markdownConsume(markdowntext, MARKDOWNUNKNOWN);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 40 "markdown.grammar"
{markdownConsume(markdowntext, MARKDOWNUNKNOWN);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 42 "markdown.grammar"
ECHO;
	YY_BREAK
#line 1053 "lex.markdown.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed markdownin at a new source and called
			 * markdownlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = markdownin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( markdownwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * markdowntext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of markdownlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					markdownrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			markdownrestart(markdownin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) markdownrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 183 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 183 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 182);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					markdownrestart(markdownin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( markdownwrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve markdowntext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void markdownrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        markdownensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            markdown_create_buffer(markdownin,YY_BUF_SIZE );
	}

	markdown_init_buffer(YY_CURRENT_BUFFER,input_file );
	markdown_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void markdown_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		markdownpop_buffer_state();
	 *		markdownpush_buffer_state(new_buffer);
     */
	markdownensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	markdown_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (markdownwrap()) processing, but the only time this flag
	 * is looked at is after markdownwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void markdown_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	markdownin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE markdown_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) markdownalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in markdown_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) markdownalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in markdown_create_buffer()" );

	b->yy_is_our_buffer = 1;

	markdown_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with markdown_create_buffer()
 * 
 */
    void markdown_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		markdownfree((void *) b->yy_ch_buf  );

	markdownfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a markdownrestart() or at EOF.
 */
    static void markdown_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	markdown_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then markdown_init_buffer was _probably_
     * called from markdownrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void markdown_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		markdown_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void markdownpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	markdownensure_buffer_stack();

	/* This block is copied from markdown_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from markdown_switch_to_buffer. */
	markdown_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void markdownpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	markdown_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		markdown_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void markdownensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)markdownalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in markdownensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)markdownrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in markdownensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE markdown_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) markdownalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in markdown_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	markdown_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to markdownlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       markdown_scan_bytes() instead.
 */
YY_BUFFER_STATE markdown_scan_string (yyconst char * yystr )
{
    
	return markdown_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to markdownlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE markdown_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) markdownalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in markdown_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = markdown_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in markdown_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up markdowntext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		markdowntext[markdownleng] = (yy_hold_char); \
		(yy_c_buf_p) = markdowntext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		markdownleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int markdownget_lineno  (void)
{
        
    return markdownlineno;
}

/** Get the input stream.
 * 
 */
FILE *markdownget_in  (void)
{
        return markdownin;
}

/** Get the output stream.
 * 
 */
FILE *markdownget_out  (void)
{
        return markdownout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t markdownget_leng  (void)
{
        return markdownleng;
}

/** Get the current token.
 * 
 */

char *markdownget_text  (void)
{
        return markdowntext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void markdownset_lineno (int  line_number )
{
    
    markdownlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see markdown_switch_to_buffer
 */
void markdownset_in (FILE *  in_str )
{
        markdownin = in_str ;
}

void markdownset_out (FILE *  out_str )
{
        markdownout = out_str ;
}

int markdownget_debug  (void)
{
        return markdown_flex_debug;
}

void markdownset_debug (int  bdebug )
{
        markdown_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from markdownlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    markdownin = stdin;
    markdownout = stdout;
#else
    markdownin = (FILE *) 0;
    markdownout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * markdownlex_init()
     */
    return 0;
}

/* markdownlex_destroy is for both reentrant and non-reentrant scanners. */
int markdownlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		markdown_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		markdownpop_buffer_state();
	}

	/* Destroy the stack itself. */
	markdownfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * markdownlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *markdownalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *markdownrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void markdownfree (void * ptr )
{
	free( (char *) ptr );	/* see markdownrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 42 "markdown.grammar"



int markdownwrap(void){return 1;}


